services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: libreria
    ports:
      - "5432:5432"
    #    volumes:
    #      - postgres_data:/var/lib/postgresql/data
    networks:
      - libreria
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d mi_basedatos"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend/backend-libreria
      dockerfile: Dockerfile
    container_name: libreria-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/libreria
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    expose:
      - "8080"
    networks:
      - libreria

  #volumes:
  #  postgres_data:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "81:80"
    depends_on:
      - db
    networks:
      - libreria



networks:
  libreria:
    driver: bridge